---
name: Net-OBEX-Packet-Headers
version: 0.001
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: construct and parse OBEX packet headers
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
build_requires:
  Test::More: 0
provides:
  Net::OBEX::Packet::Headers:
    file: lib/Net/OBEX/Packet/Headers.pm
    version: 0.001
  Net::OBEX::Packet::Headers::Byte1:
    file: lib/Net/OBEX/Packet/Headers/Byte1.pm
    version: 0.001
  Net::OBEX::Packet::Headers::Byte4:
    file: lib/Net/OBEX/Packet/Headers/Byte4.pm
    version: 0.001
  Net::OBEX::Packet::Headers::ByteSeq:
    file: lib/Net/OBEX/Packet/Headers/ByteSeq.pm
    version: 0.001
  Net::OBEX::Packet::Headers::Unicode:
    file: lib/Net/OBEX/Packet/Headers/Unicode.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
